name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: get_version
        run: |
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          echo "FOUNDRY_MANIFEST=https://github.com/${{github.repository}}/releases/latest/download/module.json" >> $GITHUB_ENV
          echo "FOUNDRY_DOWNLOAD=https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip" >> $GITHUB_ENV

      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: restackio/update-json-file-action@v2.0
        with:
          file: './module.json'
          fields: '{"version": "${{env.VERSION}}", "manifest": "${{env.FOUNDRY_MANIFEST}}", "download": "${{env.FOUNDRY_DOWNLOAD}}"}'

      - name: Zip
        run: zip -r ./module.zip * -x "./assets/screenshots/*" -x "./README.md"

      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        id: create_version_release
        with:
          allowUpdates: true
          name: ${{ github.event.release.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json, ./module.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
          prerelease: ${{ github.event.release.prerelease }}
          makeLatest: false

      - name: Publish Module to FoundryVTT Website
        if: ${{ !github.event.release.prerelease }}
        id: publish-to-foundry-website
        uses: cs96and/FoundryVTT-release-package@v1
        with:
          package-token: ${{ secrets.RELEASE_TOKEN }}
          manifest-url: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.json
          notes-url: https://github.com/${{github.repository}}/releases/tag/${{github.event.release.tag_name}}
